// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzBZ425hES9ruHhqNgcPqCcis7RF25QYU',
    appId: '1:942606579452:web:55a18fde7f45ab0889c979',
    messagingSenderId: '942606579452',
    projectId: 'fir-flutter-d5b97',
    authDomain: 'fir-flutter-d5b97.firebaseapp.com',
    storageBucket: 'fir-flutter-d5b97.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTBjUuJZ-t9u3Zumqzbhk5Q3XiYzbhhec',
    appId: '1:942606579452:android:e80fb0ef4ca4c34289c979',
    messagingSenderId: '942606579452',
    projectId: 'fir-flutter-d5b97',
    storageBucket: 'fir-flutter-d5b97.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKl2ZvAcuEuWsFC2z95FebO7GH_RXlo-I',
    appId: '1:942606579452:ios:d9a61e054358169189c979',
    messagingSenderId: '942606579452',
    projectId: 'fir-flutter-d5b97',
    storageBucket: 'fir-flutter-d5b97.appspot.com',
    iosBundleId: 'com.gabrielaAOV.landingpage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKl2ZvAcuEuWsFC2z95FebO7GH_RXlo-I',
    appId: '1:942606579452:ios:0fa2bb832484410c89c979',
    messagingSenderId: '942606579452',
    projectId: 'fir-flutter-d5b97',
    storageBucket: 'fir-flutter-d5b97.appspot.com',
    iosBundleId: 'com.example.test01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzBZ425hES9ruHhqNgcPqCcis7RF25QYU',
    appId: '1:942606579452:web:673b82459141e89189c979',
    messagingSenderId: '942606579452',
    projectId: 'fir-flutter-d5b97',
    authDomain: 'fir-flutter-d5b97.firebaseapp.com',
    storageBucket: 'fir-flutter-d5b97.appspot.com',
  );
}
